name: Linux CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: actions-setup-cmake
      uses: jwlawson/actions-setup-cmake@v1.2
      with:
        cmake-version: '3.7.x'
    - name: install pkg-config
      run: sudo apt-get install pkg-config
    - name: install uuid-dev
      run: sudo apt-get install uuid-dev
    - name: install antlr4
      run: sudo apt-get install antlr4
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build
    - name: build test
      run: cd build && cmake -DWITH_TEST=ON .. && make
    - name: test
      run: cd build && ctest

